### ISSUE TITLE
Remove or optionalize informational console.log messages

### ISSUE THREAD

**Issue by ctgraham** [bryklaus/glpc_related-entries#25]
The relatedEntries.js has a number of informational / debug log messages.  These should be removed, or we should add a debug flag which can enable these selectively.
https://github.com/bryklaus/glpc_related-entries/blob/c9664e21e61a8ce154aa5847458be8fb05ac2c0a/app/src/static/js/relatedEntries.js#L41
https://github.com/bryklaus/glpc_related-entries/blob/c9664e21e61a8ce154aa5847458be8fb05ac2c0a/app/src/static/js/relatedEntries.js#L52
https://github.com/bryklaus/glpc_related-entries/blob/c9664e21e61a8ce154aa5847458be8fb05ac2c0a/app/src/static/js/relatedEntries.js#L55
https://github.com/bryklaus/glpc_related-entries/blob/c9664e21e61a8ce154aa5847458be8fb05ac2c0a/app/src/static/js/relatedEntries.js#L441

**Comment by bryklaus** [comment]
Agreed. Maybe we just comment them?

**Comment by ctgraham** [comment]
I should test the changes before merging rather than just doing a read-through.  `process.ENV` won't exist in the non-node static js.  We'll need to key this on an `envsubst` instead.

**Comment by bryklaus** [comment]
Right, I knew I was missing one last step from last time we did that. Thanks for catching.On Oct 2, 2023, at 08:12, Clinton Graham ***@***.***> wrote:﻿
I should test the changes before merging rather than just doing a read-through.  process.ENV won't exist in the non-node static js.  We'll need to key this on an envsubst instead.
