### ISSUE TITLE
Are the HOST_FILE, USER_FILE, DB_FILE sources still valid?

### ISSUE THREAD

**Issue by ctgraham** [bryklaus/glpc_related-entries#9]
Is this still a valid construct, or has it been replaced by the environment configuration?

https://github.com/bryklaus/glpc_related-entries/blob/f8c7b379eb2321c5f9efe69c3c15eda77924839a/app/src/db.js#L19-L22

**Comment by bryklaus** [comment]
This code was adopted straight from the Docker tutorial app, which I used at the beginning to learn how to write the db route file, and since it worked I did not remove or change it. Since the app doesn't use or specify HOST_FILE, USER_FILE or DB_FILE in .env, I assume it would be fine to redefine host, user, password, and database as "process.env.______" and get rid of the "x ? y : Z" syntax?

**Update: Fixed with this: https://github.com/bryklaus/glpc_related-entries/pull/1/commits**
